### ISSUE TITLE
ReferenceError: utils is not defined

### ISSUE THREAD

**Issue by rharing** [kentcdodds/js-mocking-fundamentals#1]
cloned this repo, did a npm i then npm t and the error occurred:
PASS jest src/tests/spy.js
FAIL jest src/tests/external-mock-module.js
● returns winner

ReferenceError: utils is not defined

  13 | 
  14 |   // cleanup
> 15 |   utils.getWinner.mockReset()
     |   ^
  16 | })
  17 | 
I thought lets but this course as i got tired of all the blogs that claimed to work but dont and now here are same problems, slightly disappointed, probably is problem between keyboard and the back of my chair :)
regards
Ronald

**Comment by kentcdodds** [comment]
Sorry @rharing! I'm honestly not sure how this happened, but it should be fixed now!

**Comment by rharing** [comment]
great thanks
