### ISSUE TITLE
jest.spyOn behaviour

### ISSUE THREAD

**Issue by Miklet** [kentcdodds/js-mocking-fundamentals#3]
Hi Kent!

I would like to ask you about `jest.spyOn`. In your course you have mentioned that `spyOn` does replace original implementation with an empty mock function. According to [Jest's documentation ](https://jestjs.io/docs/en/jest-object#jestspyonobject-methodname) and  my own experience with using that function it doesn't by default. Was that a mistake :)? 

Cheers and thank you for your awesome job!

**Comment by kentcdodds** [comment]
You're correct. Where do I say that?

**Comment by Miklet** [comment]
Here: https://testingjavascript.com/lessons/jest-restore-the-original-implementation-of-a-mocked-javascript-function-with-jest-spyon at 0:26 it starts.

**Comment by kentcdodds** [comment]
Yep. That's wrong. Thanks for letting me know. I'll look into getting that fixed.

**Comment by Miklet** [comment]
You're welcome!

**Comment by kentcdodds** [comment]
This has been fixed. Thanks!
